/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from 'ethers';
import { Provider } from '@ethersproject/providers';

import { IMigrator } from './IMigrator';

export class IMigratorFactory {
  static connect(address: string, signerOrProvider: Signer | Provider): IMigrator {
    return new Contract(address, _abi, signerOrProvider) as IMigrator;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: 'contract IERC20',
        name: 'token',
        type: 'address',
      },
    ],
    name: 'migrate',
    outputs: [
      {
        internalType: 'contract IERC20',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
